# Site settings
title: Via Coffee
email: viacoffeehouse@pm.me
description: > 
  This is a website for a coffee collective 
  located at the UWM Newman Center

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
